trigger:
  branches:
    include:
      - build

variables:
  ACR_NAME: 'ACRSumativa3Grupo06' 
  IMAGE_NAME: 'PgSql-Sumativa3-Grupo06'
  SERVICE_CONNECTION_NAME: 'acr-sumativa3-cnx' 

jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
          dockerfile: '**/Dockerfile'
          tags: |
            latest
        displayName: 'Build y Push de la imagen Docker al ACR - Postgres SQL DB'
