trigger:
  branches:
    include:
      - main

variables:
  VM_IP_PUBLICA: '52.179.165.40'  
  IMAGE_NAME: 'pgsql-sumativa3-grupo06'  
  ACR_NAME: 'acrsumativa3grupo06'  
  ACR_USERNAME: 'ACRSumativa3Grupo06' 
  ACR_PASSWORD: '2JmH5lwFGKFaiHeIvhQhmv15Ln0nh6FiLTYj1vyiOk+ACRAY88Wx'  

stages:
  - stage: Deploy
    jobs:
      - deployment: DeployToVM
        displayName: 'Desplegar Postgres a la VM'
        environment:
          name: 'Env-G6-S3'  
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    # Verificar e instalar Azure CLI en la máquina virtual
                    if ! command -v az &> /dev/null; then
                      echo "Azure CLI no está instalado. Instalando Azure CLI..."
                      export DEBIAN_FRONTEND=noninteractive
                      sudo apt-get update && \
                      sudo apt-get install -y curl && \
                      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && \
                      az --version
                    else
                      echo "Azure CLI ya está instalado."
                    fi
                  displayName: 'Verificar e Instalar Azure CLI'
                  failOnStderr: true

                - script: |
                    # Verificar e instalar Docker en la máquina virtual
                    if ! command -v docker &> /dev/null; then
                      echo "Docker no está instalado. Instalando Docker..."
                      export DEBIAN_FRONTEND=noninteractive
                      sudo apt-get update && \
                      sudo apt-get install -y \
                        apt-transport-https \
                        ca-certificates \
                        curl \
                        gnupg \
                        lsb-release && \
                      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
                      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
                      sudo apt-get update && \
                      sudo apt-get install -y docker-ce docker-ce-cli containerd.io && \
                      sudo systemctl start docker && \
                      sudo systemctl enable docker && \
                      sudo docker --version
                    else
                      echo "Docker ya está instalado."
                    fi
                  displayName: 'Verificar e Instalar Docker'
                  failOnStderr: true

                - script: |
                    # Autenticarse en Azure Container Registry utilizando nombre de usuario y contraseña
                    echo "Autenticándose en Azure Container Registry y ejecutando la imagen Docker..."
                    echo ${ACR_PASSWORD} | sudo docker login ${ACR_NAME}.azurecr.io -u ${ACR_USERNAME} --password-stdin > /dev/null 2>&1

                    # Descargar la imagen desde ACR
                    sudo docker pull ${ACR_NAME}.azurecr.io/${ACR_NAME}.azurecr.io/${IMAGE_NAME}:latest

                    # Verificar si el contenedor PostgreSQL ya está en ejecución
                    if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^pgsql_container\$"; then
                      echo "El contenedor 'pgsql_container' ya existe. Iniciándolo nuevamente..."
                      sudo docker start pgsql_container
                    else
                      echo "El contenedor 'pgsql_container' no existe. Creándolo y ejecutándolo..."
                      sudo docker run -d -p 5432:5432 --name pgsql_container \
                        -e POSTGRES_PASSWORD=Grupo06@DB \
                        -e POSTGRES_USER=grupo06_db_user \
                        -e POSTGRES_DB=grupo06_db \
                        ${ACR_NAME}.azurecr.io/${ACR_NAME}.azurecr.io/${IMAGE_NAME}:latest
                    fi

                    sudo docker ps
                  displayName: 'Descargar y ejecutar la imagen PostgreSQL desde ACR'
                  failOnStderr: true

                - script: |
                    # Mostrar la URL para conectarse a MySQL
                    echo "Conectar a MySQL en la máquina virtual con la IP: ${VM_IP_PUBLICA}, puerto: 5432"
                  displayName: 'Mostrar detalles de conexión a PostgreSQL'